export const themes = [
  "Culinária",
  "Viagens",
  "Esportes",
  "Música",
  "Cinema",
  "Tecnologia",
  "Saúde",
  "Bem-estar",
  "Artes",
  "História",
  "Literatura",
  "Cultura",
  "Moda",
  "Fotografia",
  "Jardinagem",
  "Decoração",
  "Meditação",
  "Yoga",
  "Psicologia",
  "Filosofia",
  "Ciência",
  "Astronomia",
  "Economia",
  "Política",
  "Natureza",
  "Animais",
  "Sustentabilidade",
  "Design",
  "Arquitetura",
  "Espiritualidade",
  "Astrologia",
  "Viagens de Aventura",
  "Comida Vegana",
  "Dança",
  "Jogos",
  "Mídias Sociais",
  "Empreendedorismo",
  "Carreiras",
  "Marketing",
  "Desenvolvimento Pessoal",
  "Habilidades Sociais",
  "Relações Interpessoais",
  "Paternidade/Maternidade",
  "Autocuidado",
  "Finanças Pessoais",
  "Estilo de Vida Minimalista",
  "Tecnologia Sustentável",
  "Cultura Pop",
  "Desenvolvimento Humano",
];
